[tool.poetry]
name = "poetry-web"
version = "0.1.0"
description = ""
authors = ["Ville Lampiselkä <148494501+pondbackjunior@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
